<a href="https://colab.research.google.com/github/SeethalekshmiMohan/Datascience/blob/main/Copy_of_StudentCopy_of_CO1_NumpyArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# program to create an array of all the even integers from 20 to 80
import numpy as np
x=np.arange(start =20,stop=80,step=2)
print(x)


[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


In [ ]:
#Write a program to create a numpy array and perform element-wise comparison (greater, greater_equal, less than, lesser_equal).
import numpy as np
x=np.array([10,12,23,34,26,3])
y=np.array([11,15,20,22,16,2])
print("Array A")
print(x)
print("\nArray B")
print(y)
print("A>B")
print(np.greater(x,y))
print("A>=B")
print(np.greater_equal(x,y))
print("A<B")
print(np.less(x,y))
print("A<=B")
print(np.less_equal(x,y))


Array A
[10 12 23 34 26  3]

Array B
[11 15 20 22 16  2]
A>B
[False False  True  True  True  True]
A>=B
[False False  True  True  True  True]
A<B
[ True  True False False False False]
A<=B
[ True  True False False False False]


In [ ]:
#program to multiply two given arrays of same size
import numpy as np
x=([[2,3,4],[3,6,8]])
y=([[3,5,7],[2,5,7]])
print(x)
print(y)
print(np.multiply(x,y))



[[2, 3, 4], [3, 6, 8]]
[[3, 5, 7], [2, 5, 7]]
[[ 6 15 28]
 [ 6 30 56]]


In [ ]:
#Program to save a given array to a text file and load it
import numpy as np
import os
x=np.arange(16).reshape(4,4)
print("Array")
print(x)
h='Cl1 Cl2 Cl3 Cl4'
np.savetxt("myarray.txt",x,fmt="%d",header=h)
print("\nAfter loading content")
print(np.loadtxt("myarray.txt"))

Array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

After loading content
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
